language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - '7.3'
  - '7.4'
  - '8.0'

install:
  - composer update --prefer-stable --prefer-dist

script: vendor/bin/phpunit  --coverage-text
