language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

install:
  - composer update --prefer-stable --prefer-dist

script: vendor/bin/phpunit  --coverage-text
